{% set name = "pywlgk" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pywlgk-{{ version }}.tar.gz
  sha256: 7b12472bcf19ec71065c8f9cc5449f56e8b5895138cfb560cfd3f4b66598a1e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
  run:
    - python >=3.8,<4.0

test:
  imports:
    - pywlgk
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python package computing Weisfeiler-Lehman graph kernels
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Old-Shatterhand
